config/routes.rb
Rails.application.routes.draw do

  root 'budgets#new'

  resources :houses

  resources :bills

  resources :product_types

  resources :house_bills

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy

  end

  get 'admin/index'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :budgets

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Budget Tool</title>

  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">


</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <!-- <a class="brand" href="#">Some Store</a>-->
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Budget Calculator", new_budget_path%></li>
          <li><%= link_to "Bill Payment", new_bill_path %></li>
          <li><%= link_to "News" %></li>
          <li><%= link_to "My Budgets", budgets_path %></li>
          <li><%= link_to "My Bills", houses_path %></li>
          <li><%= link_to "Sign Up", new_user_path %></li>

        </ul>

        <div class="loggedin-header">

          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= $sess_name %> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Logout', logout_path, method: :delete   %></li>
                </ul>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>







      </div>
    </div>
  </div>
</div>


<div class ="container">
  <div class="row">
  <div class="span9"><%= yield %></div>


</div>
    </div>
</body>
</html>